name: Continuous Integration

on: [push]

jobs:
  build:
    name: 'Test & Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v1
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
