name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
            ${{ runner.OS }}-
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage
      - run: bash <(curl -s https://codecov.io/bash)
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
