name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage
      - run: bash <(curl -s https://codecov.io/bash)
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
