name: Continuous Integration

on: [push]

jobs:
  build:
    name: 'Test & Build'
    runs-on: ubuntu-latest
    container: node:14

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      - name: 'Cache dependencies'
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
            ${{ runner.OS }}-
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
      - name: 'Run tests'
        run: yarn test --coverage
      - name: 'Save code coverage'
        run: bash <(curl -s https://codecov.io/bash)
      - name: 'Check code formatting'
        run: yarn format:check
      - name: 'Run linter'
        run: yarn lint
      - name: 'Build package'
        run: yarn build
